# Generated by Django 5.2.8 on 2025-11-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_bookss'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainer',
            table='trainee',
        ),
    ]
